language: java
jdk:
- oraclejdk8
after_success: mvn clean heroku:deploy-war
deploy:
  provider: heroku
  api_key:
    secure: Us2DNckrdXtWqftdXoKeYgcNDFhafAjfpITLqgFU2F6cTQQyUGNJ8F7/McpbHa2pCjWS6nDUINSKHlRZOauWOse3I1RN+K5PMHaVFVUObf+K7SM2XqMd2kwUUSR3vRwkwbFT6HTV0XcX9M3G4a011py2/IiDGQm4hdUw0Vr+rfkij5tsaHVfWDi2ZahZP3dfbn/gkAOxn56anAqaYR1p1Y3jDOQYJ7emQCWspiy3EO9xKIifW2IH3zTktXysmv5NwIZ7+qJxpQnu4CogKbDCi/0Bn4SdGQYMX1JKWt4L+bkHiMCTCubgGzfKLyWHVTVjSMWGEe9AAGPDQwcGz4HNBxCxilGmnvcwzBWwHjczoEI/SEFbUORCSByDorN4aHc3/GZB8/3C9ld8k+Ej0orBRLB0e7zwJt/vwrzf/p4JZOKCrAnoBLy7AXu9nL/BLdIyjucm+WE0qfXg79BJnmtWxJhNIqgm+aM46ToEaC4TKQKg3xOMtlxB/N2w4o4E8jeK8HcaOwNDLbg8MkMi08DLIF/I8MRmbLmQ7q7C9bSQ7JFs+Aqgy7askPGNFPy7Mltbw1Vjrl7+Ro4HS+noFYejmlIfOPFzYqpqWGtnPM/Fs733WeE8KPXplH4Rsbbj2mNzjkPN6jtawcwVjfTJuALzbMZNPPokRmMPb8b+6yUiOWM=
